namespace CellErp.Api;

public record LoginRequest(string Username, string Password);
public record StoreRequest(string Name, string? Nit, string? Address, string? Phone, string? Email, string? City, string Currency, string Language, string TimeZone, string Plan, string ModulesCsv, DateTime? LicenseExpiresAt, bool IsActive);
public record ProfileRequest(string Theme, string Language);
public record UserRequest(string Username, string DisplayName, string Password, string Role, string PermissionsCsv, bool IsActive);
public record CustomerRequest(string Name, string? Document, string? Phone, string? Email, Guid? PriceListId, string? Notes);
public record SupplierRequest(string Name, string? Nit, string? Phone, string? Email, string? Address, string? Notes);
public record ProductRequest(string Type, string Name, string Sku, string? Barcode, string? Category, string? Brand, string? Description, decimal Cost, decimal Price, decimal Stock, decimal MinStock, Guid? SupplierId, string? Location, int WarrantyDays, bool Active);
public record PhoneUnitRequest(Guid ProductId, string Brand, string Model, string? Variant, string? Capacity, string? Ram, string? Color, string Imei1, string? Imei2, string? SerialNumber, string ConditionType, string? ConditionNotes, decimal PurchaseCost, decimal SalePrice, Guid? SupplierId, DateTime PurchaseDate, string? PurchaseInvoiceNumber, int WarrantyDays, string? Notes);
public record PriceListRequest(string Name, string? Description, bool Active, List<PriceListItemRequest> Items);
public record PriceListItemRequest(Guid ProductId, decimal Price);
public record PurchaseInvoiceRequest(string InvoiceNumber, Guid SupplierId, DateTime InvoiceDate, DateTime? DueDate, string PaymentMethod, string PaymentTerms, List<PurchaseLineRequest> Lines);
public record PurchaseLineRequest(Guid ProductId, decimal Quantity, decimal UnitCost);
public record PayablePaymentRequest(decimal Amount, string Method, string? Reference);
public record SaleRequest(Guid? CustomerId, Guid? PriceListId, decimal Discount, string PaymentMethod, bool IsFinanced, Guid? FinancingPlatformId, string? FinancingReference, decimal? PlatformExpectedAmount, decimal? CommissionAmount, List<SaleLineRequest> Lines);
public record SaleLineRequest(Guid ProductId, Guid? PhoneUnitId, decimal Quantity, decimal UnitPrice);
public record CashOpenRequest(decimal OpeningBase);
public record CashMovementRequest(string Direction, string Type, decimal Amount, string Method, string? Reference, string? Notes);
public record CashCloseRequest(decimal CountedTotal, string? Notes);
public record TechnicianRequest(string Name, string? Phone, decimal CommissionPercent, bool Active);
public record TechnicianLoanRequest(Guid TechnicianId, decimal Amount, string Reason, int? Installments);
public record RepairOrderRequest(Guid CustomerId, string CustomerPhone, string Device, string? Brand, string? Model, string? ImeiOrSerial, string? PhysicalState, string? AccessoriesReceived, string ReportedDamage, string? Diagnosis, Guid? TechnicianId, decimal LaborCost, decimal Price, decimal Advance, DateTime? EstimatedAt, int WarrantyDays, string? Notes, string? PublicNotes, string Status);
public record RepairPartRequest(Guid ProductId, decimal Quantity);
public record RepairStatusRequest(string Status, string? Diagnosis, string? PublicNotes);
public record FinancingPlatformRequest(string Name, bool Active);
public record FinancingPaymentRequest(decimal Amount);
public record WarrantyRequest(string Type, Guid? SaleId, Guid? RepairOrderId, Guid? ProductId, Guid? CustomerId, string? ImeiOrSerial, DateTime StartsAt, DateTime ExpiresAt, string? Notes);
public record NotificationPreferenceRequest(bool TelegramConnected, string? TelegramChatId, string EventsCsv, bool DailySummary, string DailySummaryTime);
public record DashboardLayoutRequest(string Json);
